#!/bin/sh
echo "Unsecuring Limba installation..."
echo "Setup script can now write to the configuration file."
echo 
echo "Do not forget to run /usr/sbin/lmb-secure after configuring,"
echo "otherwise your installation might be at risk of attack."
chmod 0660 /var/lib/limba/config.inc.php
