.TH LIMBA 1 "Oct 27, 2011"
.SH NAME
limba \- php cms
.SH SYNOPSIS
.B limba
.RI [ files/filelist ]
.SH DESCRIPTION
\fBLimba\fP is a PHP/Mysql based CMS.
It uses apache or lighttpd.
.SH COMMANDS
.SH AUTHOR
This manual page was written by Ludovic Reenaers <lreenaers@ressource-toi.org>,
for the Limba project (but may be used by others).